### ISSUE TITLE
Long titles

### ISSUE THREAD

**Issue by davide-scalzo** [MikaelCarpenter/gb-native-router#10]
Hi, I am not sure how to handle long titles, would be great to default to a maxNumberOfLines of 1 where possible.

What's the best way to deal with this?

![screen shot 2015-09-22 at 14 45 16](https://cloud.githubusercontent.com/assets/749029/10020011/90ce7b86-6138-11e5-9ec6-523b5616734c.png)

**Comment by MikaelCarpenter** [comment]
Oh yea I added a fix for that, that shortens the title if it its too long, but it looks like it needs some fine tuning. 

You can go to NavBarContent.js and find `titleContent` and change it to:

```
titleContent = (
 <Text style={[styles.navbarText, this.props.titleStyle]} numberOfLines=1>
  {this.props.route.name}
 </Text>
);

// Or if that doesnt work, try

titleContent = (
 <Text style={[styles.navbarText, this.props.titleStyle]} numberOfLines=1>
  {routeName}
 </Text>
);
```

Lemme know how those work, I can't test it myself until later tonight.

**Comment by MikaelCarpenter** [comment]
Mmkay this has been fixed using the first example above.

[PR #13](https://github.com/MikaelCarpenter/gb-native-router/pull/13)
