### ISSUE TITLE
How to Route from Main Class?

### ISSUE THREAD

**Issue by ghost** [MikaelCarpenter/gb-native-router#12]
I am using customAction to pull open a menu.  That menu has buttons taht should open routes.  There appears to be no method of calling a new route from the same area that the actual "Router" is called.  This is a problem as it specifically states to use customAction={this.action} for side menus, etc.  

How would I go about doing this?

**Comment by MikaelCarpenter** [comment]
I'm actually not entirely sure, @t4t5 was the one who built customAction, so hopefully he has an answer. 

After taking a quick look, you could edit the `index.js` file and add a `toRoute` to the `getInitialState` method to try and access it from the `<Router />` component

**Comment by MikaelCarpenter** [comment]
@webwelten has added replaceRoute to handle your issue :)
