### ISSUE TITLE
Change onDidFocus to onWillFocus for smoother transitions

### ISSUE THREAD

**Issue by JonathanWi** [MikaelCarpenter/gb-native-router#15]
Currently - in the Navigator (located in the index.js of this component), the event that triggers the title change is onDidFocus, which means that the opacity transition (for the title & buttons to change) happens when the page has finished changing. In all iOS apps, this is not an expected behavior : The title and buttons must change when the page transition begins - thus changing onDidFocus by onWillFocus will allow for something that will appear more coherent.

PS: I'm also trying to figure our how to fade title and buttons according to the "swipe back" position and state, could you also look into it?

Cheers!

**Comment by AlexGustafsson** [comment]
@JonathanWi ~~Currently there's a problem with changing from onDidFocus to onWillFocus (the route in onWillFocus is undefined) since it breaks the animations. Have you found a workaround for this problem?~~ Edit: This was resolved by adding the onWillFocus event to the Navigator as well. (The event was still fired without doing it, just without the route)

I've tried doing the same thing, but the didMoveFinger (event comparable to PanResponder's move event) stops reporting movement when "dragging to go backwards". Have you found a way to do this?

**Comment by JonathanWi** [comment]
onWillFocus works great for me as well (as I stated, you must change the navigator, I stumbled upon the same issue as you when trying to make it work :smile: )

Regarding the didMoveFinger, I'm not able to get the X position past the first "drag" event; Maybe we'll need to add another listener like [this](https://github.com/kiddkai/react-native-gestures), but I'd rather find a way for the native event to broadcast the current X value.

I'll have a look into it today

**Comment by AlexGustafsson** [comment]
@JonathanWi  I'll try to post a pull request fixing the coherency of the animation as well as the stutter that I am experiencing when going back (popping a route).

**Comment by JonathanWi** [comment]
Okay great, let's keep each other updated on this going back issue

**Comment by AlexGustafsson** [comment]
I opened a pull request to fix the animation here:

[Made animations coherent as per iOS spec. #21](https://github.com/MikaelCarpenter/gb-native-router/pull/21)

I don't got any news on the swipe back animation however.

**Comment by AlexGustafsson** [comment]
@JonathanWi The pull request has been merged by @MikaelCarpenter. I've found a way to animate the navbar according to the "swipe back" gesture. I'll try to clean it up and commit a pull request today.

**Comment by JonathanWi** [comment]
@AlexGustafsson Awesome news! Can't wait to see how you did it!

**Comment by AlexGustafsson** [comment]
I'm having a hard time coming up with a "good" solution. But I've found what values correspond to the swipe animation.

#### index.js - render function for Navigator

When creating the Navigator, use a custom scene configurator. This allows us to attach a custom gesture, which we'll use to retrieve the interpolating values.

``` javascript
<Navigator
      ref="navigator"
      initialRoute={this.props.firstRoute}
      navigationBar={navigationBar}
      renderScene={this.renderScene}
      configureScene={this.configureScene} <---
      onWillFocus={this.onWillFocus}
/>
```

#### index.js - configureScene function for Navigator

Here we're basically telling the Navigator to use the standard config, with some additions. We're "hijacking" the animationInterpolators.

``` javascript
configureScene: function(route) {
    let config = route.sceneConfig || Navigator.SceneConfigs.FloatFromRight;
    let self = this;
    return {
      //"Fill out" the returned object with standard config
      ...config,
      //Replace animationInterpolators
      animationInterpolators: {
        into: function(result, value){
          //value is a value 0 - 1 and can be used for i.e. opacity animation
          return config.animationInterpolators.into(result, value);
        },
        out: function(result, value){
          //value is a value 0 - 1 and can be used for i.e. opacity animation
          return config.animationInterpolators.out(result, value);
        }
      }
    }
  }
```

#### The problem

There isn't any real breaking problem. However, the hard part is getting the value to the NavBarContent and animate it smoothly. The following works, but it's not as smooth as it could be.

### What I've tried

#### index.js - configureScene function

``` javascript
configureScene: function(route) {
        ...
        into: function(result, value){
          //value is a value 0 - 1 and can be used for i.e. opacity animation
          //Interpolation is set to be an object containing a value to pass around a reference to that object, not the static value.
          this.setState({interpolation: {value: value}});
          return config.animationInterpolators.into(result, value);
        },
        out: function(result, value){
          //value is a value 0 - 1 and can be used for i.e. opacity animation
          return config.animationInterpolators.out(result, value);
        }
        ...
}
```

#### index.js - NavBarContainer render

Here we pass the interpolating value to the NavBarContainer - the parent of NavBarContent (the part we're animating)

``` javascript
<NavBarContainer
        style={this.props.headerStyle}
        navigator={navigator}
        ...
        interpolation={this.state.interpolation} <----
      />
```

#### NavBarContainer.js - render function

Here we pass the interpolating value to the NavBarContent (the part we're animating)

``` javascript
return (
      <View style={[styles.navbarContainer, this.props.style, trans]}>
        {this.props.currentRoute.trans
          ?( <View /> )
          :( <NavBarContent
            route={this.state.previousRoute}
            ...
            willDisappear="true"
            interpolation={this.props.interpolation} <----
            /> )
        }
        <NavBarContent
          route={this.props.currentRoute}
          ...
          interpolation={this.props.interpolation} <----
        />
      </View>
)
```

#### NavBarContent.js - render function

Here we're applying the interpolating value to decide the opacity.

``` javascript
render() {
    var transitionStyle = {
      //1 - value for when animating out
      opacity: this.props.willDisappear ? 1 - this.props.interpolation.value : this.props.interpolation.value <----
    };
...
```

**Comment by MikaelCarpenter** [comment]
Closing this issue, as the original issue has been resolved. If there's swipeback issues feel free to make a new issue :)
