### ISSUE TITLE
Passing props to titleComponent?

### ISSUE THREAD

**Issue by davide-scalzo** [MikaelCarpenter/gb-native-router#16]
Hi,

I'd like to inject a search bar in the navBar, is there a way to pass it components?
It would be great to be able to pass it onChange as a prop so that something can happen in the parent component.

Also is there a way to customise how much space it takes on the navbar?

**Comment by MikaelCarpenter** [comment]
Where would you like to pass it the `onChange` from? You can do it when you push to the screen with the search bar using `this.props.toRoute({ passProps: { onChange: *whatever you want* } })`

**Comment by davide-scalzo** [comment]
My understanding was that passprops would pass the props to the new component, not the titleComponent?

I'll give it a shot tonight then.

Ps, I simply edited the flex amount of the titleComponent in your library to stretch it :)

**Comment by webwelten** [comment]
How would you pass Props in an InitialRoute to the TitleComponent?

**Comment by davide-scalzo** [comment]
Sorry @webwelten it's not documented well. It would use the same approach as `this.props.setRightProps` or `this.props.setRightProps` rather than doing it in a route.

**Comment by webwelten** [comment]
How does it work? I didn't understand it as well.

**Comment by davide-scalzo** [comment]
Say I call the Main component

```
renderMain: function () {
    var firstRoute = {
      name: 'Welcome!',
      component: Main,
      titleComponent: Search,
    };

    return (
      <Router
      firstRoute={firstRoute} />
    );
  }
```

then on Main.js

```
var Main = React.createClass({

    componentWillMount: function () {
        this.props.setTitleProps({
            onChange: this.onChange
        });
    },

    render: function () {
....
    }
});
```
