### ISSUE TITLE
What about latest react-native versions?

### ISSUE THREAD

**Issue by Olegas** [MikaelCarpenter/gb-native-router#17]
This awesome component requires react-native 0.11.0, but 0.12.0 is already released and 0.13.0-rc is published.

**Comment by MikaelCarpenter** [comment]
yea sorry i haven't gotten around to updating the versions! If you'd like to help out you can change the dependency in your local version and if everything seems to work just create a pull request for it :)

**Comment by Olegas** [comment]
At least basic usage working just fine. Ok, I'll create a PR.
