### ISSUE TITLE
How to get this.props.toRoute in child of child element

### ISSUE THREAD

**Issue by burnsting** [MikaelCarpenter/gb-native-router#18]
Forgive me if this is quite simple, but I'm new to React.

I was trying this router, since it'll enable me to put a logo in the top bar. But the buttons for navigating to another page are rendered in an element called from a tabbar, and there's no this.props.toRoute or anything in there. console.log(this.props) or console.log(this) doesn't return anything referencing the Router.

So it works like this:

Router renders component TabBar
TabBar renders component ListView with buttons.

Router > TabBar > ListView

this.props... is available in TabBar, but not in ListView (child of child). 

I've tried several ways, but wasn't able to access the Router from the ListView. While the same thing was possible with the default router (NavigatorIOS) via this.props.navigator from the ListView.

Hope this makes sense. Basically the problem is it's a child element of a child element.

**Comment by MikaelCarpenter** [comment]
yea you just pass it as props to ListView like this: `<ListView toRoute={this.props.toRoute}>` 

let me know if you need anything else :)

**Comment by burnsting** [comment]
Ah, I actually had to put it on the self-created element in the TabBar that called the ListView. Thanks a lot for the quick comment Mikael!
