### ISSUE TITLE
Unnecessary drag / pan responder

### ISSUE THREAD

**Issue by AlexGustafsson** [MikaelCarpenter/gb-native-router#25]
Is there any real reason why index.js contains a custom handler for when a user pan / drags / swipes a view in the Navigator?

The following is found in index.js line 110 and on.

``` javascript
    var didStartDrag = function(evt) {
      var x = evt.nativeEvent.pageX;
      if (x < 28) {
        this.setState({
          dragStartX: x,
          didSwitchView: false
        });
        return true;
      }
    }.bind(this);

    // Recognize swipe back gesture for navigation
    var didMoveFinger = function(evt) {
      var draggedAway = ((evt.nativeEvent.pageX - this.state.dragStartX) > 30);
      if (!this.state.didSwitchView && draggedAway) {
        this.onBack(navigator);
        this.setState({ didSwitchView: true });
      }
    }.bind(this);
```

The above code is completely unnecessary, since the Navigator itself handles the gestures through it's scene configurator. Is there a real reason to why the code is present or should I post a pull request to get rid of it?

To prove my hypotheses I've tried to disable the code without breaking any function. Please test more cases to check to see that I'm not mistaking.

**Comment by MikaelCarpenter** [comment]
This was added by @t4t5 in the original version of the module. I always assumed it was to just detect a swipe back, but if that is already handled by navigator, we can remove it.
