### ISSUE TITLE
Hiding navigation bar per route?

### ISSUE THREAD

**Issue by mikefowler** [MikaelCarpenter/gb-native-router#30]
@MikaelCarpenter, really great additions to the original repository. QQ: is it possible to hide the navigation bar on a per-route basis?

**Comment by davidLeonardi** [comment]
the `trans` parameter for a route does exactly that.

**Comment by mikefowler** [comment]
That's what I was figuring, but it seemingly just makes the background of the navbar transparent and allows the page content to flow under it. Per the screenshots, the navigation bar is still appearing in my `home` route, which has its own navigation control positioned absolutely at the top of the page.

![screen shot 2015-11-16 at 10 22 47 am](https://cloud.githubusercontent.com/assets/744542/11190729/1b39ed6c-8c4c-11e5-912e-f9a7d2b55fe9.png)

![screen shot 2015-11-16 at 10 25 06 am](https://cloud.githubusercontent.com/assets/744542/11190766/548809d2-8c4c-11e5-962e-9c7e3fa8dfcc.png)

**Comment by davidLeonardi** [comment]
I noticed this as well actually.
Ill look into it tonight as i need this in my project as well.
Will create a PR once i've implemented it

**Comment by davidLeonardi** [comment]
Implemented in the current PR as a new parameter: `hideNavigationBar` .
This now is both for the whole router or on a route level.

**Comment by davidLeonardi** [comment]
@MikaelCarpenter this can be closed now.
