### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by mtimofiiv** [MikaelCarpenter/gb-native-router#4]
Dear @MikaelCarpenter,

First of all thanks for this fork!

@t4t5's last commit to [t4t5/react-native-router](https://github.com/t4t5/react-native-router) was June 11th. It is incompatible with the newer versions of `react-native` (as you're aware).

He's also incommunicado in general.

Don't you think it's time to publish this in the NPM registry for easier installation?

**Comment by MikaelCarpenter** [comment]
Yea, i'd love to! I'm just not sure how okay that is. There's an MIT license on `react-native-router` which sounds like I can probably publish, but I'm not sure. Any advice? 

I'll probably go ahead and publish next week after a little research.

**Comment by t4t5** [comment]
@MikaelCarpenter Go ahead and publish! :) Sorry, I haven't had time to update my own library since my startup is taking up all my time currently, so it's better if people can easily use something else in the meantime. Hopefully we can join forces in the future!

**Comment by MikaelCarpenter** [comment]
oh okay awesome! I'll get it published asap :)

**Comment by MikaelCarpenter** [comment]
Mmkay node module officially published. [Link](https://www.npmjs.com/package/gb-native-router)

Can change `package.json` dependencies to: `"gb-native-router": "^0.4.0"`

**Comment by mtimofiiv** [comment]
Thanks! That was fast!
