### ISSUE TITLE
Problem with peerDependencies while installing

### ISSUE THREAD

**Issue by jvlobo** [MikaelCarpenter/gb-native-router#42]
Hi there.

I was trying to install this module but I've received this errors:

![captura de pantalla 2015-11-28 a las 10 42 13](https://cloud.githubusercontent.com/assets/5671420/11451206/fbfc155e-95bc-11e5-8fa3-10c6bdc36f43.png)

I don't know what it is or how to solve it. I hope you guys can help me.

Thanks.

**Comment by davidLeonardi** [comment]
So, my knowledge of NPM package management is a bit insufficient. Can anybody advise what the best strategy is here? Since RN updates on a weekly/biweekly cycle, whats the best option here? Update our release every week/s or change this to be very accomodating for future versions?

**Comment by grabbou** [comment]
Translating that into more readable version:

> `gb-native-router` wants react-native >= 0.12.0 in its peer dependencies but 0.16.0-rc was installed.

The problem is that your package specifies `>= 0.12.0` in its peerDependencies. That does not work for rc, beta, alpha and all other versions added with `-`, e.g. `0.12.0-rc2`.

In order to make that working again, you have to update `peerDependencies` here https://github.com/MikaelCarpenter/gb-native-router/blob/master/package.json#L31 to  `>= 0.12.0 || 0.16.0-rc` but that's not going to work with any other previous RC, e.g. 0.8.0-rc (which is fine though since no one should be using them now)

**Comment by jvlobo** [comment]
So, there is not a definitive solution, right??

And I'm not be able to change that by myself, I have to wait for the module's creator to do it, is that right?

Thanks.

**Comment by davidLeonardi** [comment]
I patched that up in the Pull request referenced above. Just copy that code into your node_modules folder.. We have to wait for @MikaelCarpenter to merge and make a new release.

**Comment by jvlobo** [comment]
@sethx although I copy that code into my node_modules folder, it doesn't work anyway.

When I do npm install gb-native-router or npm install gb-native-router --save it overwrites my package.json

**Comment by davidLeonardi** [comment]
@jvlobo: Why not stick to 0.15.0 ? Is there anything you absolutely need from a RC version?

**Comment by jvlobo** [comment]
I don't think so, I've just updated React Native and this is the latest version, nothing else...

**Comment by davidLeonardi** [comment]
It's a prerelease version, you're better off using 0.15.0 or you will most likely run into even more bugs than usual :) just downgrade whatever is depending on 0.16.0rc

**Comment by jvlobo** [comment]
Thanks a lot buddy, with that version it works perfect :)

**Comment by davidLeonardi** [comment]
Welcome!

**Comment by jvlobo** [comment]
The module is correctly installed but there are a bunch of errors by downgrading React Native to 0.15.0 :/

**Comment by davidLeonardi** [comment]
Such as?

**Comment by jvlobo** [comment]
http://puu.sh/lD1LF/5b536e3a0f.png

**Comment by davidLeonardi** [comment]
That's a whole different issue altogether.
I'd say your node_modules folder is borked. Delete it and redo npm install.

**Comment by grabbou** [comment]
To workaround it manually, upgrade to npm3 that ignores that requirement.

**Comment by jvlobo** [comment]
I'm still having this problem... I was waiting for @MikaelCarpenter to see if he accepts @sethx pull requests but it seems like he's not over here.

So, I updated package.json inside gb-native-router module folder and when I go to run my project on Xcode I get this:

<img width="1004" alt="captura de pantalla 2015-12-02 a las 21 06 36" src="https://cloud.githubusercontent.com/assets/5671420/11542644/9e9acdae-9938-11e5-86c8-e9d7ef28001c.png">

I don't know if you guys could help me out with this because I'm unable to develop this project because of those errors.

Thanks :)

**Comment by MikaelCarpenter** [comment]
@sethx so I'm merging the PR to update the dependencies for now, but is this really best practice for a module? 

Would it be better to require the most recent versions of RN or allow a large range of versions?
