### ISSUE TITLE
Go back to previous view by pushing a button

### ISSUE THREAD

**Issue by jvlobo** [MikaelCarpenter/gb-native-router#48]
Hi there.

I'd like to add to my app a button to go to the previous screen.

I'd like the same behavior as when I swipe right from the left side of the screen, which go back to the previous screen.

I don't know if that is possible. I hope I have explained it well.

Thanks :)

**Comment by jamesfzhang** [comment]
I'm also interested in this feature. Something along the lines of `this.props.popRoute()` to go back to previous route.

**Comment by jamesfzhang** [comment]
@jvlobo From looking over the source code, it looks like you can do this:

``` js
function goBack() {
  this.props.toBack(this.props.navigator);
}
```

`toBack` and `navigator` are properties that the router automatically sets on the rendered component.

**Comment by jvlobo** [comment]
Awesome @jamesfzhang !!! thank you so much :)
