### ISSUE TITLE
Disable swipe back

### ISSUE THREAD

**Issue by jamesfzhang** [MikaelCarpenter/gb-native-router#49]
Thanks for maintaining this router, I find it much easier to use than Navigator. Is there a way to disable swiping to go back? Navigator did it by [disabling `gestures`](https://github.com/facebook/react-native/issues/1014). Is that possible here? Thanks :)

**Comment by charpeni** [comment]
You can disable swipe back with `gestures` too.

``` javascript
let sceneConfig = Navigator.SceneConfigs.FloatFromRight;
sceneConfig.gestures = {};

this.props.toRoute({
  name: "A new screen",
  component: HelloPage,
  sceneConfig: sceneConfig,
});
```

**Comment by jamesfzhang** [comment]
@Charpeni Fantastic, thank you!
