### ISSUE TITLE
Header/Topbar

### ISSUE THREAD

**Issue by jvlobo** [MikaelCarpenter/gb-native-router#5]
Hi, I already have my own topbar and I was wondering if it is possible to disable it in the router component, because my app looks like this:

http://puu.sh/k7qGI/8aabf3e6bf.png

Thanks.

**Comment by MikaelCarpenter** [comment]
Yup! `<Router hideNavigationBar=true />` gets rid of it. Also you can move all those components you have into the navigation bar if you'd rather do that.

**Comment by jvlobo** [comment]
Thanks for your help @MikaelCarpenter but apparently it doesn't work, I guess I have to set true between braces { true } right?

Even so it doesn't work

http://puu.sh/k7BZF/f586548453.png

**Comment by MikaelCarpenter** [comment]
Ooh do you mean the content sits too low? If so I would just recommend moving your header components into the navbar. That's kind of what it's for.. 

That being said, `hideNavigationBar=true` should still move the content up to the top, so I'll have a fix out for that in like less than an hour :)

**Comment by jvlobo** [comment]
Oh that would be great.

I mean, maybe I could try to move my code to the navbar, but it seems like I can't even change the height on this navbar and I need more flexibility.

Thank you so much.

**Comment by MikaelCarpenter** [comment]
There ya go, PR merged :)

**Comment by jvlobo** [comment]
Sorry for open the issue again, your commit worked well, but I'm having another trouble with the top of the screen in my app, here is a screenshot: http://puu.sh/k7EBn/d1c0f42c01.png

It seems like some view inside the Router tag is adding some margin top and I don't know how to remove this :/

Thanks

**Comment by MikaelCarpenter** [comment]
yea that's supposed to be for the status bar (the data carrier, time, and battery). That margin is to account for that. Are you hiding the status bar in your app?

**Comment by jvlobo** [comment]
Yep, my status bar is hidden

**Comment by MikaelCarpenter** [comment]
k gimme like 10 min

**Comment by jvlobo** [comment]
You're awesome man.

I've seen another error, that I'd see it didn't happen before I updated with your changed, and it is when I go to another view, if I want to go back by slide from the left to the right, I get this error: http://puu.sh/k7Fkc/a3943c584b.png

Thanks.

**Comment by MikaelCarpenter** [comment]
Mmkay added a `noStatusBar=true` that works if `hideNavigationBar` is also true. And I'm not getting that error, my swipe to go back works fine.

**Comment by jvlobo** [comment]
Ok @MikaelCarpenter I'm very appreciate

Your fixes work really well, also I re-run the project in Xcode and it seems like I don't get this error when swipe back so it works fine. Perfect :+1: 

Thanks.
