### ISSUE TITLE
Scene transition doesn't respect background color

### ISSUE THREAD

**Issue by jamesfzhang** [MikaelCarpenter/gb-native-router#52]
I have 2 screens where the backgrounds are both black, but in the transition there's a flash of white where the initial scene gets replaced. Is there a way to either pass in a background color to the router?

![screencast](https://cloud.githubusercontent.com/assets/2057670/11903200/58ea9e70-a56c-11e5-9e0a-215df9fc4a60.gif)

**Comment by jamesfzhang** [comment]
I just needed to set the background color of the overall app.

**Comment by charpeni** [comment]
> set the background color of the overall app.

@jamesfzhang How did you do that?

**Comment by jamesfzhang** [comment]
@charpeni I just set the background of the `Router`.

``` jsx
<Router hideNavBar={true} style={{ backgroundColor: '#00000' }}>
```

**Comment by charpeni** [comment]
@jamesfzhang I tried to put a backgroundColor everywhere including on `Router` and it does not change, it remains white .. Weird, I will continue to check that, thank you!
