### ISSUE TITLE
Invaliant Violation when back to first Route

### ISSUE THREAD

**Issue by paulomenezes** [MikaelCarpenter/gb-native-router#56]
Hi everybody.

I'm trying to do a Logout in my app, but when I try to back my first route I get this error:

![screen shot 2016-01-11 at 17 15 43](https://cloud.githubusercontent.com/assets/10564179/12245426/25841b00-b887-11e5-97fd-6c0669d1b4d9.png)

index.ios.js:

``` javascript
<Router 
    headerStyle={ styles.header } 
    backButtonComponent={BackButton} 
    rightCorner={Search}
    firstRoute={ {
        name: 'Login',
        component: Login
    } } />
```

logout.js

``` javascript
this.props.nav.resetToRoute({
    name: 'Login',
    component: Login
});
```

Someone know why I get this error?

Thnks

**Comment by kesha-antonov** [comment]
@paulomenezes Hello!
Can you explain how did you solve it please?

**Comment by paulomenezes** [comment]
I remove my require('login') at top of page and insert it inside on click function.
When you want back to route, not insert the require at top of file.

**Comment by kesha-antonov** [comment]
Thanks! @paulomenezes
