### ISSUE TITLE
Navbar animation flickering on toRoute

### ISSUE THREAD

**Issue by sercanov** [MikaelCarpenter/gb-native-router#8]
I think it's related to opacity animation. When I using left button component to route next page, in the beginning of the opacity transition animation, it seems like to re-render previous component like in a milisecs. 

I digged deep into NavBarContent and I find out it's related to code block below. I commented out the block and it seems to work fine but I don't know if any complications are going to happen ^^
      `this.setState({
         opacity: this.props.willDisappear ? 1 : 0
       });`

**Comment by sercanov** [comment]
aaand opacity animation is gone ^^

**Comment by MikaelCarpenter** [comment]
Do you mind making a gif of the problem? I normally use [licecap](http://www.cockos.com/licecap/) for that.
